# Generated by Django 5.1.15 on 2026-04-26 08:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0003_alter_pokerroom_is_active_alter_pokerroom_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'bubble option',
                'verbose_name_plural': 'bubble options',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EarlyBirdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'early bird type',
                'verbose_name_plural': 'early bird types',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReEntryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 're-entry option',
                'verbose_name_plural': 're-entry options',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('game_type', models.CharField(choices=[('NLHE', "No-Limit Hold'em"), ('PLO', 'Pot-Limit Omaha'), ('PLO5', '5-card PLO'), ('PLO8', 'Omaha Hi/Lo (8-or-better)'), ('STUD', 'Stud'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], default='NLHE', max_length=8, verbose_name='game type')),
                ('buy_in_total_cents', models.PositiveBigIntegerField(verbose_name='buy-in (with rake), cents')),
                ('buy_in_without_rake_cents', models.PositiveBigIntegerField(verbose_name='buy-in (without rake), cents')),
                ('rake_cents', models.PositiveBigIntegerField(verbose_name='rake, cents')),
                ('guaranteed_dollars', models.PositiveBigIntegerField(help_text='Whole dollars. Stored separately from buy-ins because GTDs are always quoted in round numbers.', verbose_name='guaranteed prize pool ($)')),
                ('payout_percent', models.PositiveSmallIntegerField(help_text='Percentage of the field that gets paid.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='payout distribution (%)')),
                ('starting_stack', models.PositiveIntegerField(verbose_name='starting chips')),
                ('starting_stack_bb', models.PositiveIntegerField(verbose_name='starting chips (BB)')),
                ('starting_time', models.DateTimeField(verbose_name='starting time')),
                ('late_reg_at', models.DateTimeField(verbose_name='late registration closes at')),
                ('late_reg_level', models.PositiveSmallIntegerField(verbose_name='late registration level')),
                ('blind_interval_minutes', models.PositiveSmallIntegerField(verbose_name='blind interval (minutes)')),
                ('break_minutes', models.PositiveSmallIntegerField(verbose_name='break time (minutes)')),
                ('players_per_table', models.PositiveSmallIntegerField(verbose_name='players per table')),
                ('players_at_final_table', models.PositiveSmallIntegerField(verbose_name='players at the final table')),
                ('min_players', models.PositiveIntegerField(verbose_name='min players')),
                ('max_players', models.PositiveIntegerField(verbose_name='max players')),
                ('early_bird', models.BooleanField(verbose_name='early bird')),
                ('featured_final_table', models.BooleanField(verbose_name='featured final table')),
                ('submitted_for_review', models.BooleanField(default=False, verbose_name='submitted for review')),
                ('verified_by_admin', models.BooleanField(default=False, verbose_name='verified by superadmin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.bubbleoption', verbose_name='bubble')),
                ('early_bird_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.earlybirdtype', verbose_name='early bird type')),
                ('re_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.reentryoption', verbose_name='re-entry')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='rooms.pokerroom', verbose_name='room')),
            ],
            options={
                'verbose_name': 'tournament',
                'verbose_name_plural': 'tournaments',
                'ordering': ('starting_time',),
            },
        ),
        migrations.CreateModel(
            name='BlindStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='level')),
                ('small_blind', models.PositiveIntegerField(verbose_name='small blind')),
                ('big_blind', models.PositiveIntegerField(verbose_name='big blind')),
                ('ante', models.PositiveIntegerField(default=0, verbose_name='ante')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_levels', to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'blind level',
                'verbose_name_plural': 'blind levels',
                'ordering': ('tournament', 'level'),
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['starting_time'], name='tournaments_startin_214e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['room', 'starting_time'], name='tournaments_room_id_fdb28c_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['buy_in_total_cents'], name='tournaments_buy_in__dc533b_idx'),
        ),
        migrations.AddConstraint(
            model_name='blindstructure',
            constraint=models.UniqueConstraint(fields=('tournament', 'level'), name='uniq_tournament_level'),
        ),
    ]
