# Generated by Django 5.1.15 on 2026-04-23 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Stable identifier from the source room (tournament ID).', max_length=128, verbose_name='external id')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('game_type', models.CharField(choices=[('NLHE', "No-Limit Hold'em"), ('PLO', 'Pot-Limit Omaha'), ('PLO5', '5-card PLO'), ('PLO8', 'Omaha Hi/Lo (8-or-better)'), ('STUD', 'Stud'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], default='NLHE', max_length=8, verbose_name='game type')),
                ('tournament_format', models.CharField(choices=[('freezeout', 'Freezeout'), ('rebuy', 'Rebuy'), ('reentry', 'Re-entry'), ('bounty', 'Bounty'), ('ko', 'Knockout'), ('pko', 'Progressive KO'), ('satellite', 'Satellite'), ('sitngo', 'Sit & Go')], default='freezeout', max_length=16, verbose_name='format')),
                ('table_size', models.CharField(choices=[('hu', 'Heads-Up'), ('6max', '6-max'), ('9max', '9-max (Full Ring)'), ('other', 'Other')], default='9max', max_length=8, verbose_name='table size')),
                ('buy_in_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='buy-in (cents)')),
                ('rake_cents', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='rake (cents)')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 code, e.g. USD, EUR, RUB.', max_length=3, verbose_name='currency')),
                ('starting_stack', models.PositiveIntegerField(blank=True, null=True, verbose_name='starting stack')),
                ('start_at', models.DateTimeField(verbose_name='start time')),
                ('late_reg_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='late registration (minutes)')),
                ('blind_level_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='blind level duration (minutes)')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='estimated duration (minutes)')),
                ('final_table_size', models.PositiveSmallIntegerField(default=9, verbose_name='final table size')),
                ('blind_reset_at_final', models.BooleanField(default=False, verbose_name='blind reset at final table')),
                ('blind_reset_level', models.PositiveSmallIntegerField(blank=True, help_text='Level the blinds reset to when the final table forms.', null=True, verbose_name='blind reset level')),
                ('avg_entrants', models.PositiveIntegerField(blank=True, null=True, verbose_name='average entrants')),
                ('avg_blinds_at_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='average BB at final table')),
                ('source_kind', models.CharField(choices=[('scraped', 'Scraped'), ('manual', 'Manual')], default='manual', max_length=16, verbose_name='source')),
                ('scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='scraped at')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='raw scraper payload')),
                ('verified_by_admin', models.BooleanField(default=False, verbose_name='verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='rooms.pokerroom', verbose_name='room')),
            ],
            options={
                'verbose_name': 'tournament',
                'verbose_name_plural': 'tournaments',
                'ordering': ('start_at',),
            },
        ),
        migrations.CreateModel(
            name='BlindStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='level')),
                ('small_blind', models.PositiveIntegerField(verbose_name='small blind')),
                ('big_blind', models.PositiveIntegerField(verbose_name='big blind')),
                ('ante', models.PositiveIntegerField(default=0, verbose_name='ante')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Overrides the tournament default for this level only.', null=True, verbose_name='duration (minutes)')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_levels', to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'blind level',
                'verbose_name_plural': 'blind levels',
                'ordering': ('tournament', 'level'),
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_started_at', models.DateTimeField(verbose_name='actual start')),
                ('entrants', models.PositiveIntegerField(verbose_name='entrants')),
                ('final_table_avg_bb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='average BB at final table')),
                ('total_prize_pool_cents', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total prize pool (cents)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'tournament result',
                'verbose_name_plural': 'tournament results',
                'ordering': ('-instance_started_at',),
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_at'], name='tournaments_start_a_52fcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['room', 'start_at'], name='tournaments_room_id_b20be6_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['buy_in_cents'], name='tournaments_buy_in__804141_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('room', 'external_id'), name='uniq_room_external_id'),
        ),
        migrations.AddConstraint(
            model_name='blindstructure',
            constraint=models.UniqueConstraint(fields=('tournament', 'level'), name='uniq_tournament_level'),
        ),
        migrations.AddConstraint(
            model_name='tournamentresult',
            constraint=models.UniqueConstraint(fields=('tournament', 'instance_started_at'), name='uniq_tournament_instance'),
        ),
    ]
