# Generated by Django 5.1.15 on 2026-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_drop_scraper_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='submitted_for_review',
            field=models.BooleanField(default=False, verbose_name='submitted for review'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='verified_by_admin',
            field=models.BooleanField(default=False, verbose_name='verified by superadmin'),
        ),
    ]
