# Generated by Django 5.1.15 on 2026-04-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_periodicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='submitted_for_review',
        ),
    ]
