# Generated by Django 5.1.15 on 2026-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_tournament_submitted_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone name; controls how starting/late-reg times are interpreted on input.', max_length=64, verbose_name='timezone'),
        ),
    ]
