# Generated by Django 5.1.15 on 2026-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='late_registration_available',
            field=models.BooleanField(default=True, help_text='Uncheck if the tournament has no late-registration window. The stored close-time will then equal the starting time.', verbose_name='late registration available'),
        ),
    ]
