# Generated by Django 5.1.15 on 2026-04-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_late_registration_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='late_registration_available',
            field=models.BooleanField(default=True, help_text='Uncheck if the tournament has no late-registration.', verbose_name='late registration available'),
        ),
    ]
