# Generated by Django 5.1.15 on 2026-04-29 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_tournament_late_registration_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='late_reg_level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='late registration level'),
        ),
    ]
