# Generated by Django 5.1.15 on 2026-04-30 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournament_late_reg_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='blind_interval_minutes',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='blind interval (minutes)'),
        ),
    ]
