# Generated by Django 5.1.15 on 2026-04-30 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_alter_tournament_blind_interval_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='break time (minutes)'),
        ),
    ]
