# Generated by Django 5.1.15 on 2026-04-30 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_tournament_break_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players_at_final_table',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='players at the final table'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players_per_table',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='players per table'),
        ),
    ]
