# Generated by Django 5.1.15 on 2026-04-30 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_alter_tournament_players_at_final_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='max players'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='min_players',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2)], verbose_name='min players'),
        ),
    ]
