# Generated by Django 5.1.15 on 2026-04-30 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_tournament_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveIntegerField(default=8000, validators=[django.core.validators.MinValueValidator(2)], verbose_name='max players'),
        ),
    ]
