# Generated by Django 5.1.15 on 2026-04-30 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_tournament_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='starting_stack',
            field=models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='starting chips'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='starting_stack_bb',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='starting chips (BB)'),
        ),
    ]
