# Generated by Django 5.1.15 on 2026-05-02 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_buyin_cents_to_dollars'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tournament',
            new_name='tournaments_buy_in__f317bf_idx',
            old_name='tournaments_buy_in_total_idx',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='blind_interval_minutes',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='blind interval, min'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='break time, min'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('NLHE', 'NL Holdem'), ('PLO', 'Pot-Limit Omaha'), ('PLO5', '5-card PLO'), ('PLO8', 'Omaha Hi/Lo (8-or-better)'), ('STUD', 'Stud'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], default='NLHE', max_length=8, verbose_name='game type'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='guaranteed_dollars',
            field=models.PositiveBigIntegerField(help_text='Whole dollars. Stored separately from buy-ins because GTDs are always quoted in round numbers.', verbose_name='guaranteed prize pool, $'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='payout_percent',
            field=models.PositiveSmallIntegerField(help_text='Percentage of the field that gets paid.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='payout distribution, %'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='starting_stack_bb',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='starting chips, BB'),
        ),
    ]
