# Generated by Django 5.1.15 on 2026-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_verbose_name_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='weekdays',
            field=models.PositiveSmallIntegerField(default=127, help_text='Days of the week the tournament runs on. Ignored when periodicity is one-off.', verbose_name='active weekdays'),
        ),
    ]
