# Generated by Django 5.1.15 on 2026-05-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_tournamentseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentseries',
            name='image',
            field=models.ImageField(blank=True, upload_to='series/', verbose_name='image'),
        ),
    ]
