# Generated by Django 5.1.15 on 2026-05-17 21:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_seed_pokerok_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealMakingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'deal-making option',
                'verbose_name_plural': 'deal-making options',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveIntegerField(default=8000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='max players'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='min_players',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='min players'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='deal_making',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.dealmakingoption', verbose_name='deal making'),
        ),
    ]
