# Generated by Django 5.1.15 on 2026-05-18 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_seed_dealmakingoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='payout_percent',
            field=models.PositiveSmallIntegerField(default=15, help_text='Percentage of the field that gets paid.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='payout distribution, %'),
        ),
    ]
