# Generated by Django 5.1.15 on 2026-05-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_trim_children_beyond_room_horizon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindStructureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blind structure template',
                'verbose_name_plural': 'blind structure templates',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlindLevelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='level')),
                ('small_blind', models.PositiveIntegerField(verbose_name='small blind')),
                ('big_blind', models.PositiveIntegerField(verbose_name='big blind')),
                ('ante', models.PositiveIntegerField(default=0, verbose_name='ante')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='tournaments.blindstructuretemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'blind level (template)',
                'verbose_name_plural': 'blind levels (template)',
                'ordering': ('template', 'level'),
                'constraints': [models.UniqueConstraint(fields=('template', 'level'), name='uniq_template_level')],
            },
        ),
    ]
