# Generated by Django 5.1.15 on 2026-05-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_extract_blind_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blindstructuretemplate',
            name='description',
        ),
    ]
