# Generated by Django 5.1.15 on 2026-05-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_remove_blindstructuretemplate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='early_bird',
            field=models.BooleanField(default=False, verbose_name='early bird'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='early_bird_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.earlybirdtype', verbose_name='early bird type'),
        ),
    ]
