# Generated by Django 5.1.15 on 2026-05-26 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_alter_tournament_early_bird_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='early_bird_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.earlybirdtype', verbose_name='early bird'),
        ),
    ]
