# Generated by Django 5.1.15 on 2026-06-02 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0032_weekdays_to_local_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'bounty option',
                'verbose_name_plural': 'bounty options',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='bounty_buyin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portion of the buy-in funding the bounty pool. 0 for non-bounty events.', max_digits=10, verbose_name='buy-in to bounty pool, $'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_bounty',
            field=models.BooleanField(default=False, verbose_name='bounty'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_bounty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Smallest bounty paid per knockout.', max_digits=10, null=True, verbose_name='minimum bounty, $'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='buy_in_without_rake',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='buy-in to prize pool, $'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bounty_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.bountyoption', verbose_name='bounty'),
        ),
    ]
