# Generated by Django 5.1.15 on 2026-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0034_seed_bounty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='external_key',
            field=models.CharField(blank=True, help_text='Stable signature of a scraped recurring definition; the import match key for the scrape pipeline. Empty for manually-entered tournaments.', max_length=255, null=True, unique=True, verbose_name='external key'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last seen in feed'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('scraped', 'Scraped')], default='manual', max_length=16, verbose_name='source'),
        ),
    ]
