# Generated by Django 5.1.15 on 2026-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0035_tournament_external_key_tournament_last_seen_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('feed_size', models.PositiveIntegerField(default=0, verbose_name='items in feed')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='created')),
                ('updated', models.PositiveIntegerField(default=0, verbose_name='updated')),
                ('unchanged', models.PositiveIntegerField(default=0, verbose_name='unchanged')),
                ('errored', models.PositiveIntegerField(default=0, verbose_name='with errors')),
                ('missing_from_feed', models.PositiveIntegerField(default=0, verbose_name='missing from feed')),
            ],
            options={
                'verbose_name': 'scrape run',
                'verbose_name_plural': 'scrape runs',
                'ordering': ('-started_at',),
            },
        ),
    ]
