# Generated by Django 5.1.15 on 2026-04-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_backfill_role_from_flags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'superadmin')), fields=('role',), name='single_superadmin'),
        ),
    ]
