# Generated by Django 5.1.15 on 2026-04-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_single_superadmin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='single_superadmin',
        ),
    ]
