# Generated by Django 5.1.15 on 2026-04-25 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_single_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChangeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_role', models.CharField(blank=True, max_length=16, verbose_name='old role')),
                ('new_role', models.CharField(max_length=16, verbose_name='new role')),
                ('source', models.CharField(choices=[('admin', 'Django admin'), ('cli', 'Management command'), ('signup', 'Signup flow'), ('other', 'Other')], default='other', max_length=16, verbose_name='source')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='changed at')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_audits', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'role change',
                'verbose_name_plural': 'role changes',
                'ordering': ('-changed_at',),
                'indexes': [models.Index(fields=['-changed_at'], name='users_rolec_changed_b4edf1_idx'), models.Index(fields=['user', '-changed_at'], name='users_rolec_user_id_cff17a_idx')],
            },
        ),
    ]
