# Generated by Django 5.1.15 on 2026-04-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rolechangeaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_break_glass',
            field=models.BooleanField(default=False, help_text='Marks this row as an emergency-only SUPERADMIN. The account is hidden from the default admin list view; document its credentials offline and only sign in to recover from a lost main SUPERADMIN.', verbose_name='break-glass account'),
        ),
    ]
