# Generated by Django 5.1.15 on 2026-05-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_break_glass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], default='en', max_length=10, verbose_name='preferred language'),
        ),
    ]
