# Generated by Django 5.1.15 on 2026-05-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='table_pref_json',
            field=models.JSONField(blank=True, default=dict, help_text='Column order/visibility, sort and filter state for the tournament table.', verbose_name='table preferences'),
        ),
    ]
