# Generated by Django 5.1.15 on 2026-04-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('website', models.URLField(blank=True, verbose_name='website')),
            ],
            options={
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PokerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='Stable identifier used as the scraper_key and in external IDs.', max_length=64, unique=True, verbose_name='slug')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('is_active', models.BooleanField(default=True, help_text='When false, scrapers skip this room and filters hide it.', verbose_name='active')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.network', verbose_name='network')),
            ],
            options={
                'verbose_name': 'poker room',
                'verbose_name_plural': 'poker rooms',
                'ordering': ('name',),
            },
        ),
    ]
