# Generated by Django 5.1.15 on 2026-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_seed_mvp_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerroom',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When false, the room is hidden from filters and the public list.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='pokerroom',
            name='slug',
            field=models.SlugField(help_text='Stable identifier used in URLs and external references.', max_length=64, unique=True, verbose_name='slug'),
        ),
    ]
