# Generated by Django 5.1.15 on 2026-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_pokerroom_is_active_alter_pokerroom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerroom',
            name='image',
            field=models.ImageField(blank=True, upload_to='rooms/', verbose_name='image'),
        ),
    ]
