# Generated by Django 5.1.15 on 2026-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_pokerroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerroom',
            name='horizon_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='How many days of recurring tournament children to materialize forward for tournaments hosted by this room.', verbose_name='horizon (days)'),
        ),
    ]
